### ISSUE TITLE
Oprócz historii wydań potrzebowałabym też historię przyjęć.

### ISSUE THREAD

**Issue by immunochomik** [immunochomik/workwear#1]
Opisz ta historie przyjec?
Myślę o czymś analogicznym do historii wydań. Czyli żebym mogła zobaczyć w jakiejś tabelce zbiór wprowadzanych do Inventory pozycji z datą przyjęcia.

**Comment by immunochomik** [comment]
No dobrze mamy historie przyjec wiec jak dodasz wpis to dodaje do inventory,
co zrobic gdy edytujesz istniejacy wpis z histori przyjec ?

**Comment by Ocia86** [comment]
podobnie jak w przypadku historii wydań - jeżeli zmienię istniejący wpis z historii przyjęć to dlatego, że się np. pomyliłam przy wprowadzaniu i wprowadziłam do inventory nie to co trzeba. Edytowanie historii przyjęć musiałoby wpływać na zasób inventory, inaczej nie miałoby sensu. Ważna dla mnie przy wprowadzaniu pozycji do historii przyjęć jest jeszcze data przyjęcia.
