### ISSUE TITLE
Historia wydan 

### ISSUE THREAD

**Issue by immunochomik** [immunochomik/workwear#5]
blocked by autocomplete 
1 day

**Comment by immunochomik** [comment]
still need taking stuff of from inventory

**Comment by immunochomik** [comment]
Zastnow sie co mamy zrobic jak w sytuacji gdy chcesz edytwac istniejacy wpis w histori wydan, jak ma to wplynac na inventory,   
na razie bedize tak ze jak dodajesz wpis to sciaga z inventory (do minimum 0), 
co zrobic jak skasujesz ten wpis? albo go edytujesz, czy powinienem dodac to do inventory ?

**Comment by Ocia86** [comment]
Jeżeli edytuję wpis w historii wydań to zapewne dlatego, że zmieni się to co wydałam (np. pracownik stwierdzi następnego dnia rano, że jednak dostał za duży rozmiar) i w takim razie analogicznie powinien się zmienić stan inventory (w naszym przykładzie większy rozmiar powinien wrócić na stan, a mniejszy, który pracownik ostatecznie dostał powinien ze stanu zejść; w przypadku usunięcia pozycji z historii wydań teoretycznie element powinien wrócić do inventory). Pytanie tylko, czy nie będzie to wymagało od Ciebie za dużo pracy. Zawsze można takie sytuacje rozwiązać przyjęciem towaru jako zwrot i wydaniem nowej pozycji. Więc można by było w ogóle usunąć opcję edytowania i usuwania pozycji w historii wydań (oczywiście po wcześniejszym wyczyszczeniu tych próbnych pozycji).
