### ISSUE TITLE
Sizes

### ISSUE THREAD

**Issue by Ocia86** [immunochomik/workwear#8]
Zastanawiam się czy sizes powinno być przypisane na stałe do pracownika, czy nie lepiej przy release history. Bo jak teraz wydam pracownikowi koszulkę XL, za rok schudnie i wydam L, to jak zmienię mu rozmiar w jego właściwościach, to czy nie narobi się bałagan w inventory (bo tam jak rozumiem automatycznie zaczytuje jaki pracownik ściąga ze stanu jaki rozmiar)? Nie zmieni się, że rok wcześniej też dostał L zamiast XL?
Podobnie zdarzają się sytuacje, że wyjdą mi wszystkie kurtki męskie i wydaję facetom damskie. A to nie znaczy, że facet zmienił płeć, czy rozmiar. A jakoś tę damską muszę ze stanu ściągnąć i przypisać do tego faceta. Damy radę to jakoś zmienić?
Nie wiem tylko wtedy na jakiej podstawie program miałby przewidywać zapotrzebowanie. Bo nie chciałabym, żeby na podstawie historii przewidział, że ten facet znowu dostanie damską kurtkę. Masakra to jest.

**Comment by immunochomik** [comment]
No wiec ja bym zostawil rozmiar na pracowniku, bo tylko tak mozemy przewidziec zapotrzebowanie, A wydawac mozesz co chcesz komu chcesz, i jak im sie zmieni rozmiar to musisz zmienic romiar temu pracownikowi.    

Przewidywanie wydan bedzie na bazie pracownik wymiary -> stanowisko  i tyle.   
Jak wydajesz przez historie wydan to dzieja sie dwie rzeczy dodaje do histori wydan i probuje sciagnac z inventarza (do minimum zero nie bedzie sciagac ponizej jezeli nie masz czegos w inventarzu),  tu jest pewnie problem co zrobic jezeli chcesz usunac zapis z histori wydan albo go edytowac) otworze na to osobne issu

**Comment by immunochomik** [comment]
takze wydawanie nie zmienia wlasciwosci pracownika takze nic sie nie popsuje jak wydasz cos niezgodnie z danymi pracownika

**Comment by immunochomik** [comment]
Zobacz inne issu czy nie zostawilem tam jakichs pytan do Ciebie.
